cocktail_master/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cocktails.urls')),
]

cocktails/urls.py
"""Defines URL patterns for cocktails."""

from django.urls import path
from . import views

app_name = 'cocktails'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that displays all ingredients
    path('ingredients/', views.ingredients, name='ingredients'),
    # Detail page for an Ingredient.
    path('ingredients/<int:ingredient_id>/',
         views.ingredient, name='ingredient'),
    # Page for adding new ingredient.
    path('ingredients/new_ingredient/',
         views.new_ingredient, name='new_ingredient'),
    # Page for editing ingredient.
    path('ingredients/<int:ingredient_id>/edit',
         views.edit_ingredient, name='edit_ingredient'),
    # Page for deleting ingredient.
    path('ingredients/<int:ingredient_id>/delete',
         views.delete_ingredient, name='delete_ingredient'),

    # Page that displays all cocktails
    path('cocktails/', views.cocktails, name='cocktails'),
    # Detail page for a Cocktail.
    path('cocktails/<int:cocktail_id>/', views.cocktail, name='cocktail'),
    # Page for adding new cocktail.
    path('cocktails/new_cocktail/', views.new_cocktail, name='new_cocktail'),
    # Page for editing ingredient.
    path('cocktails/<int:cocktail_id>/edit', views.edit_cocktail,
         name='edit_cocktail'),
    # Page for deleting ingredient.
    path('cocktails/<int:cocktail_id>/delete', views.delete_cocktail,
         name='delete_cocktail'),

]

cocktails/models.py
from django.db import models
from django.db.models.functions import Length

models.CharField.register_lookup(Length)


class Ingredient(models.Model):
    """Ingredient for cocktails."""
    name = models.CharField(max_length=30)
    description = models.TextField()

    class Meta:
        constraints = [
            models.CheckConstraint(name="ingredient_name_not_empty",
                                   check=models.Q(name__length__gt=0)),
            models.UniqueConstraint(name="ingredient_name_unique",
                                    fields=["name"]),
        ]

    def __str__(self):
        """Return a string representation of the model."""
        return self.name


class Cocktail(models.Model):
    """Cocktail model."""
    name = models.CharField(max_length=30)
    description = models.TextField()
    steps = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    ingredients = models.ManyToManyField(
        Ingredient,
        through='Recipe',
        through_fields=('cocktail', 'ingredient'),
    )

    class Meta:
        constraints = [
            models.CheckConstraint(name="cocktail_name_not_empty",
                                   check=models.Q(name__length__gt=0)),
            models.UniqueConstraint(name="cocktail_name_unique",
                                    fields=["name"]),
        ]

    def __str__(self):
        """Return a string representation of the model."""
        return self.name


class Recipe(models.Model):
    """Recipe model."""
    cocktail = models.ForeignKey(Cocktail, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.PROTECT)
    quantity = models.IntegerField()

    class Meta:
        constraints = [
            models.CheckConstraint(name="quantity_gt_0",
                                   check=models.Q(quantity__gt=0)),
        ]

    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.quantity} ml of {self.ingredient}"

cocktails/forms.py
# from django.forms import ModelForm, HiddenInput, IntegerField, CharField
from django import forms

from .models import Ingredient, Cocktail, Recipe


class IngredientForm(forms.ModelForm):
    """Form for adding ingredients"""
    class Meta:
        model = Ingredient
        fields = ['name', 'description']


class RecipeForm(forms.ModelForm):
    """Form for adding ingredients"""

    class Meta:
        model = Recipe
        fields = ['ingredient', 'quantity']
        labels = {'ingredient': '', 'quantity': ''}

    # Change default order for ingredient field to sorting by ingredient name
    def __init__(self, *args, **kwargs):
        super(RecipeForm, self).__init__(*args, **kwargs)
        self.fields['ingredient'].queryset = self.fields['ingredient'].queryset.order_by('name')

    def clean(self):
        cleaned_data = super().clean()

        # Check that quantity is gt 0
        if cleaned_data["quantity"] <= 0:
            self.add_error(None, f"Quantity must be greater then zero")

        return cleaned_data


class CocktailForm(forms.ModelForm):
    """Form for adding ingredients"""

    class Meta:
        model = Cocktail
        fields = ['name', 'description', 'steps']

cocktails/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import modelformset_factory
from django.core.paginator import Paginator
from django.db.models import Q

from .models import Cocktail, Ingredient, Recipe
from .forms import IngredientForm, RecipeForm, CocktailForm


def index(request):
    """The home page for Cocktails."""
    return render(request, 'cocktails/index.html')


def ingredients(request):
    """Show all ingredients"""
    query = request.GET.get('q')
    if query:
        ingredients = Ingredient.objects.filter(
            name__icontains=query).order_by('name')
    else:
        ingredients = Ingredient.objects.order_by('name')

    paginator = Paginator(ingredients, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'page_obj': page_obj}
    return render(request, 'cocktails/ingredients.html', context)


def ingredient(request, ingredient_id):
    """Show a single ingredient."""
    ingredient = get_object_or_404(Ingredient, id=ingredient_id)
    context = {'ingredient': ingredient, 'description': ingredient.description}
    return render(request, 'cocktails/ingredient.html', context)


def new_ingredient(request):
    """Add new ingredient."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = IngredientForm()
    else:
        # POST data submitted; process data.
        form = IngredientForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('cocktails:ingredients')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'cocktails/new_ingredient.html', context)


def edit_ingredient(request, ingredient_id):
    """Edit ingredient."""
    ingredient = get_object_or_404(Ingredient, id=ingredient_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = IngredientForm(instance=ingredient)
    else:
        # POST data submitted; process data.
        form = IngredientForm(instance=ingredient, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('cocktails:ingredient',
                            ingredient_id=ingredient_id)

    # Display a blank or invalid form.
    context = {'ingredient': ingredient, 'form': form}
    return render(request, 'cocktails/edit_ingredient.html', context)


def delete_ingredient(request, ingredient_id):
    """Delete ingredient."""
    ingredient = get_object_or_404(Ingredient, id=ingredient_id)
    cocktails = Cocktail.objects.filter(ingredients__id=ingredient_id)

    if request.method == 'POST':
        ingredient.delete()
        return redirect('cocktails:ingredients')

    context = {'ingredient': ingredient, 'cocktails': cocktails}
    return render(request, 'cocktails/delete_ingredient.html', context)


def cocktails(request):
    """Show all cocktails"""
    query = request.GET.get('q')
    if query:
        cocktails = Cocktail.objects.filter(
            Q(name__icontains=query) |
            Q(ingredients__name__icontains=query)).order_by('name').distinct()
    else:
        cocktails = Cocktail.objects.order_by('name')

    paginator = Paginator(cocktails, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'page_obj': page_obj}
    return render(request, 'cocktails/cocktails.html', context)


def cocktail(request, cocktail_id):
    """Show a single cocktail."""
    cocktail = get_object_or_404(Cocktail, id=cocktail_id)
    ingredients = Recipe.objects.filter(cocktail=cocktail)
    context = {'cocktail': cocktail,
               'description': cocktail.description,
               'ingredients': ingredients,
               'steps': cocktail.steps}
    return render(request, 'cocktails/cocktail.html', context)


def new_cocktail(request):
    """Add a new cocktail."""

    IngredientsFormset = modelformset_factory(Recipe, form=RecipeForm)
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = CocktailForm()
        formset = IngredientsFormset(queryset=Recipe.objects.none())
    else:
        # POST data submitted; process data.
        form = CocktailForm(data=request.POST)
        formset = IngredientsFormset(request.POST)
        if form.is_valid() and formset.is_valid():
            cocktail = form.save()
            ingredients = formset.save(commit=False)
            for ingredient in ingredients:
                ingredient.cocktail = cocktail
                ingredient.save()
            return redirect('cocktails:cocktails')

    # Display a blank or invalid form.
    context = {'form': form, 'formset': formset}
    return render(request, 'cocktails/new_cocktail.html', context)


def edit_cocktail(request, cocktail_id):
    """Edit cocktail."""
    cocktail = get_object_or_404(Cocktail, id=cocktail_id)
    IngredientsFormset = modelformset_factory(Recipe, form=RecipeForm)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = CocktailForm(instance=cocktail)
        formset = IngredientsFormset(queryset=Recipe.objects.filter(
            cocktail=cocktail))
    else:
        # POST data submitted; process data.
        form = CocktailForm(instance=cocktail, data=request.POST)
        formset = IngredientsFormset(request.POST)
        if form.is_valid() and formset.is_valid():
            cocktail = form.save()
            ingredients = formset.save(commit=False)
            for ingredient in ingredients:
                ingredient.cocktail = cocktail
                ingredient.save()
            return redirect('cocktails:cocktails')

    # Display a blank or invalid form.
    context = {'cocktail': cocktail, 'form': form, 'formset': formset}
    return render(request, 'cocktails/edit_cocktail.html', context)


def delete_cocktail(request, cocktail_id):
    """Delete cocktail."""
    cocktail = get_object_or_404(Cocktail, id=cocktail_id)

    if request.method == 'POST':
        cocktail.delete()
        return redirect('cocktails:cocktails')

    context = {'cocktail': cocktail}
    return render(request, 'cocktails/delete_cocktail.html', context)

cocktails/templates/cocktails/base.html
{% load bootstrap5 %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
  <title>"I drink"</title>
  {% bootstrap_css %}
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-primary mb-4 border">
    <a class="navbar-brand" href="{% url 'cocktails:index' %}">
      <h1 class="display-4">"I drink"</h1>
    </a>
    <ul class="navbar-nav mr-auto">
      <h2><a class="nav-link" href="{% url 'cocktails:cocktails' %}">Cocktails</a></h2>
    </ul>
    <ul class="navbar-nav mr-auto">
      <h2><a class="nav-link" href="{% url 'cocktails:ingredients' %}">Ingredients</a></h2>
    </ul>
  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom" style="max-width:800px;">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div style="max-width:800px;">
      {% block content %}{% endblock content %}
    </div>
  </main>
</body>

cocktails/templates/cocktails/cocktail.html
{% extends 'cocktails/base.html' %}

{% block page_header %}
  <h3>{{ cocktail }}</h3>
{% endblock page_header %}

{% block content %}

  <div class="card mb-2">
    <h4 class="card-header">Description:</h4>
    <div class="card-body">
      {{ description|linebreaks }}
    </div>
  </div>

  <div class="card mb-2">
    <h4 class="card-header">Ingredients</h4>
    <ul>
      {% for ingredient in ingredients %}
        <li><a href="{% url 'cocktails:ingredient' ingredient.ingredient.id %}">{{ ingredient }}</a></li>
      {% empty %}
        <li>No ingredients have been added yet.</li>
      {% endfor %}
    </ul>
  </div>

  <div class="card mb-2">
    <h4 class="card-header">Steps:</h4>
    <div class="card-body">
      {{ steps|linebreaks }}
    </div>
  </div>
  <a href="{% url 'cocktails:edit_cocktail' cocktail.id %}"
  class="btn btn-outline-secondary" role="button">Edit</a>
  <a href="{% url 'cocktails:delete_cocktail' cocktail.id %}"
  class="btn btn-outline-danger" role="button">Delete</a>

{% endblock content %}

cocktails/templates/cocktails/cocktails.html
{% extends "cocktails/base.html" %}
{% load custom_tags %}

{% block page_header %}
  <h1>Cocktails</h1>
{% endblock page_header %}

{% block content %}

  <form action="{% url 'cocktails:cocktails' %}" method="get">
    <h3><input name="q" type="text" placeholder="Search..."></h3>
  </form>

  <h3><a href="{% url 'cocktails:new_cocktail' %}">Add new cocktail</a></h3>

  <ul>
    {% for cocktail in page_obj %}
      <li><h3>
        <a href="{% url 'cocktails:cocktail' cocktail.id %}">{{ cocktail }}</a>
      </h3></li>
    {% empty %}
      <li><h3>Nothing here.</h3></li>
    {% endfor %}
  </ul>

  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
        <a href="?{% param_replace page=1 %}">&laquo; first</a>
        <a href="?{% param_replace page=page_obj.previous_page_number %}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
        <a href="?{% param_replace page=page_obj.next_page_number %}">next</a>
        <a href="?{% param_replace page=paginator.num_pages %}">last &raquo;</a>
      {% endif %}
    </span>
  </div>

{% endblock content %}

cocktails/templates/cocktails/delete_cocktail.html
{% extends "cocktails/base.html" %}

{% load crispy_forms_tags %}

{% block page_header %}
  <h3>Delete cocktail:</h3>
{% endblock page_header %}

{% block content %}

  <h5>Are you want to delete the cocktail {{cocktail}}?</h5>
  <form action="{% url 'cocktails:delete_cocktail' cocktail.id%}" method='post'>
    {% csrf_token %}
    <button type="submit" class="btn btn-outline-danger">Yes, I'm sure</button>
  </form>

{% endblock content %}

cocktails/templates/cocktails/delete_ingredient.html
{% extends "cocktails/base.html" %}

{% load crispy_forms_tags %}

{% block page_header %}
  <h3>Delete ingredient:</h3>
{% endblock page_header %}

{% block content %}

  {% if cocktails %}
    <h4>Cannot delete ingredient:</h4>
    <h5>
      Deleting the ingredient {{ingredient}} would require deleting
      the following cocktails:
    </h5>
    <ul>
      {% for cocktail in cocktails %}
        <li><h5>
          <a href="{% url 'cocktails:cocktail' cocktail.id %}">{{ cocktail }}</a>
        </h5></li>
      {% endfor %}
      </ul>
  {% else %}
    <h5>Are you want to delete the ingredient {{ingredient}}?</h5>
    <form action="{% url 'cocktails:delete_ingredient' ingredient.id%}" method='post'>
      {% csrf_token %}
      <button type="submit" class="btn btn-outline-danger">Yes, I'm sure</button>
    </form>
  {% endif %}

{% endblock content %}

cocktails/templates/cocktails/edit_cocktail.html
{% extends "cocktails/base.html" %}

{% block page_header %}
  <h3>Edit cocktail:</h3>
{% endblock page_header %}

{% block content %}

  <form id="form-container" action="{% url 'cocktails:edit_cocktail' cocktail.id%}" method='post'>
    {% csrf_token %}

    <div class="form-group mb-2">
      <label for="id_{{form.name.name}}">Cocktail name</label>
      <input type="text"
        class="form-control"
        name="{{form.name.name}}"
        id="id_{{form.name.name}}"
        value="{{form.name.value}}"
        required>
      <small id="passwordHelpInline" class="text-danger">
        {{form.errors.name}}
      </small>
    </div>

    <div class="form-group mb-2">
      <label for="id_{{form.description.name}}">Description</label>
      <textarea
        class="form-control"
        rows="5"
        name="{{form.description.name}}"
        id="id_{{form.description.name}}"
        placeholder="Description"
        required>{{form.description.value}}</textarea>
    </div>

    <div class="form-group mb-2">
      <label for="id_{{form.steps.name}}">Steps</label>
      <textarea
        class="form-control"
        rows="5"
        name="{{form.steps.name}}"
        id="id_{{form.steps.name}}"
        required>{{form.steps.value}}</textarea>
    </div>

    {{formset.management_form}}
    Add ingredients and quantity
    {% for f_form in formset %}
      <div class="ingredients-form mb-2">
        {{ f_form }}
      </div>
    {% endfor %}
    <button id="add-form" class="btn btn-outline-secondary">Add ingredient</button>
    <button type="submit" class="btn btn-outline-primary">Save changes</button>
  </form>

  <script>
    let ingredientsForm = document.querySelectorAll(".ingredients-form")
    let container = document.querySelector("#form-container")
    let addButton = document.querySelector("#add-form")
    let totalForms = document.querySelector("#id_form-TOTAL_FORMS")

    let formNum = ingredientsForm.length-1
    addButton.addEventListener('click', addForm)

    function addForm(e){
      e.preventDefault()
      let newForm = ingredientsForm[0].cloneNode(true)
      let formRegex = RegExp(`form-(\\d){1}-`,'g')

      formNum++
      newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`)
      container.insertBefore(newForm, addButton)

      totalForms.setAttribute('value', `${formNum+1}`)
    }
  </script>

{% endblock content %}

cocktails/templates/cocktails/edit_ingredient.html
{% extends "cocktails/base.html" %}

{% block page_header %}
  <h3>Edit ingredient:</h3>
{% endblock page_header %}

{% block content %}

  <form action="{% url 'cocktails:edit_ingredient' ingredient.id%}" method='post'>
    {% csrf_token %}
    <div class="form-group mb-2">
      <label for="id_{{form.name.name}}">Ingredient name</label>
      <input type="text"
        class="form-control"
        name="{{form.name.name}}"
        id="id_{{form.name.name}}"
        value="{{form.name.value}}"
        required>
      <small id="passwordHelpInline" class="text-danger">
        {{form.errors.name}}
      </small>
    </div>
    <div class="form-group mb-2">
      <label for="id_{{form.description.name}}">Description</label>
      <textarea
        class="form-control"
        rows="5"
        name="{{form.description.name}}"
        id="id_{{form.description.name}}"
        required>{{form.description.value}}</textarea>
    </div>
    <button type="submit" class="btn btn-outline-primary">Save changes</button>
  </form>

{% endblock content %}

cocktails/templates/cocktails/index.html
{% extends "cocktails/base.html" %}

{% block page_header %}
  <div class="jumbotron">
    <h1 class="display-3">"I drink".</h1>
    <p class="lead">"I drink" contains the list of cocktails and how to make them.</p>
  </div>
{% endblock page_header %}

cocktails/templates/cocktails/ingredient.html
{% extends 'cocktails/base.html' %}

{% block page_header %}
  <h3>{{ ingredient }}</h3>
{% endblock page_header %}

{% block content %}

  <div class="card mb-2">
    <div class="card-body">
      {{ description|linebreaks }}
    </div>
  </div>
  <a href="{% url 'cocktails:edit_ingredient' ingredient.id %}"
  class="btn btn-outline-secondary" role="button">Edit</a>
  <a href="{% url 'cocktails:delete_ingredient' ingredient.id %}"
  class="btn btn-outline-danger" role="button">Delete</a>
{% endblock content %}

cocktails/templates/cocktails/ingredients.html
{% extends "cocktails/base.html" %}
{% load custom_tags %}

{% block page_header %}
  <h1>Ingredients</h1>
{% endblock page_header %}

{% block content %}

  <form action="{% url 'cocktails:ingredients' %}" method="get">
    <h3><input name="q" type="text" placeholder="Search..."></h3>
  </form>

  <h3><a href="{% url 'cocktails:new_ingredient' %}">Add new ingredient</a></h3>

  <ul>
    {% for ingredient in page_obj %}
      <li><h3>
        <a href="{% url 'cocktails:ingredient' ingredient.id %}">{{ ingredient }}</a>
      </h3></li>
    {% empty %}
      <li><h3>Nothing here.</h3></li>
    {% endfor %}
  </ul>

  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
        <a href="?{% param_replace page=1 %}">&laquo; first</a>
        <a href="?{% param_replace page=page_obj.previous_page_number %}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
        <a href="?{% param_replace page=page_obj.next_page_number %}">next</a>
        <a href="?{% param_replace page=paginator.num_pages %}">last &raquo;</a>
      {% endif %}
    </span>
  </div>

{% endblock content %}

cocktails/templates/cocktails/new_cocktail.html
{% extends "cocktails/base.html" %}

{% block page_header %}
  <h3>Add new cocktail:</h3>
{% endblock page_header %}

{% block content %}

  <form id="form-container" action="{% url 'cocktails:new_cocktail' %}" method='post'>
    {% csrf_token %}

    <div class="form-group mb-2">
      <label for="id_{{form.name.name}}">Cocktail name</label>
      <input type="text"
        class="form-control"
        name="{{form.name.name}}"
        id="id_{{form.name.name}}"
        placeholder="Name"
        required>
      <small id="passwordHelpInline" class="text-danger">
        {{form.errors.name}}
      </small>
    </div>

    <div class="form-group mb-2">
      <label for="id_{{form.description.name}}">Description</label>
      <textarea
        class="form-control"
        rows="5"
        name="{{form.description.name}}"
        id="id_{{form.description.name}}"
        placeholder="Description"
        required></textarea>
    </div>

    <div class="form-group mb-2">
      <label for="id_{{form.steps.name}}">Steps</label>
      <textarea
        class="form-control"
        rows="5"
        name="{{form.steps.name}}"
        id="id_{{form.steps.name}}"
        placeholder="Steps"
        required></textarea>
    </div>

    {{formset.management_form}}
    Add ingredients and quantity
    {% for f_form in formset %}
      <div class="ingredients-form mb-2">
        {{ f_form }}
      </div>
    {% endfor %}
    <button id="add-form" class="btn btn-outline-secondary">Add ingredient</button>
    <button type="submit" class="btn btn-outline-primary">Save cocktail</button>
  </form>

  <script>
    let ingredientsForm = document.querySelectorAll(".ingredients-form")
    let container = document.querySelector("#form-container")
    let addButton = document.querySelector("#add-form")
    let totalForms = document.querySelector("#id_form-TOTAL_FORMS")

    let formNum = ingredientsForm.length-1
    addButton.addEventListener('click', addForm)

    function addForm(e){
      e.preventDefault()
      let newForm = ingredientsForm[0].cloneNode(true)
      let formRegex = RegExp(`form-(\\d){1}-`,'g')

      formNum++
      newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`)
      container.insertBefore(newForm, addButton)

      totalForms.setAttribute('value', `${formNum+1}`)
    }
  </script>

{% endblock content %}

cocktails/templates/cocktails/new_ingredient.html
{% extends "cocktails/base.html" %}

{% block page_header %}
  <h3>Add new ingredient:</h3>
{% endblock page_header %}

{% block content %}

  <form action="{% url 'cocktails:new_ingredient' %}" method='post'>
    {% csrf_token %}
    <div class="form-group mb-2">
      <label for="id_{{form.name.name}}">Ingredient name</label>
      <input type="text"
        class="form-control"
        name="{{form.name.name}}"
        id="id_{{form.name.name}}"
        placeholder="Name"
        required>
      <small id="passwordHelpInline" class="text-danger">
        {{form.errors.name}}
      </small>
    </div>
    <div class="form-group mb-2">
      <label for="id_{{form.description.name}}">Description</label>
      <textarea
        class="form-control"
        rows="5"
        name="{{form.description.name}}"
        id="id_{{form.description.name}}"
        placeholder="Description"
        required></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Save ingredient</button>
  </form>

{% endblock content %}